server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: blog-server
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 451311677zxg

  # redis配置
  redis:
    # redis服务器地址
    host: 129.28.41.113
    # redis服务器连接端口
    port: 6379
    # redis服务器索引（默认为0）
    database: 0
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 50
        # 连接池最大阻塞的古代时间（使用负值表示没有限制）
        max-wait: 3000
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池中的最小空闲连接
        min-idle: 2
    # 连接超时时间（毫秒）
    timeout: 5000

mybatis:
  mapper-locations: classpath:mapper/*.xml

  type-aliases-package: com.xaut.blog.entities #所有Entity别名类所在包
  configuration:
    # 配置数据库下划线字段转驼峰
    map-underscore-to-camel-case: true
    # 执行SQL语句打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#eureka:
#  client:
#    # 是否将自己注册进eureka Server ,默认为true
#    register-with-eureka: true
#    # 是否从Eureka Server 抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合 Ribbon 使用负载均衡
#    fetch-registry: true
#    service-url:
#      # 单机版
#      # defaultZone: http://localhost:7001/eureka
#      # 集群版
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#  instance:
#    # 微服务实例主机名称
#    instance-id: payment8001
#    # 应该优先使用服务器的IP地址，而不是操作系统报告的主机名。访问路径可以显示ip地址
#    prefer-ip-address: true
#    # Eureka 客户端向服务端发送心跳的时间间隔，默认30s,单位s
#    lease-renewal-interval-in-seconds: 30
#    # Eureka 客户端在收到最后一次心跳后等待的时间上限，单位s(默认90)，超时建剔除服务
#    lease-expiration-duration-in-seconds: 90